# Generated by Django 5.1.15 on 2026-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_shipping_fee_order_tracking_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
