# Generated by Django 5.1 on 2026-04-27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="checkout_reference",
            field=models.CharField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                max_length=36,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status"], name="orders_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "created_at"], name="orders_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["product", "order"], name="orderitem_prod_order_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["product", "expires_at"], name="stockres_prod_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["user", "order"], name="stockres_user_order_idx"),
        ),
    ]
