# Generated by Django 5.1 on 2026-04-27

from django.db import migrations
import core.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_checkout_reference_tracking_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=core.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=core.encryption.EncryptedCharField(blank=True),
        ),
    ]
