# Generated by Django 5.1.15 on 2026-05-08 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_encryption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_user_id_17dbdf_idx',
            old_name='orders_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_status_11db6c_idx',
            old_name='orders_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='order_items_product_efdd3a_idx',
            old_name='orderitem_prod_order_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='stock_reser_product_e6f7d5_idx',
            old_name='stockres_prod_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='stock_reser_user_id_98620f_idx',
            old_name='stockres_user_order_idx',
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', 'created_at'], name='page_views_user_id_0cec42_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_key', 'created_at'], name='page_views_session_9c12f0_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['created_at'], name='page_views_created_5023bb_idx'),
        ),
    ]
