# Generated by hand: add sku field to Product
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_orders_user_status_idx_orders_user_id_17dbdf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=64, blank=True, db_index=True),
            preserve_default=False,
        ),
    ]
