# Generated by hand: change Order.shipping_address from TextField to CharField(500)
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_add_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=500),
        ),
    ]
