# Generated by hand: add an index to Product.name for faster search lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_change_shipping_address_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
