# Generated by Django 5.1 on 2026-04-27

from django.db import migrations, models
import core.encryption


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=core.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=core.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=core.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=core.encryption.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=core.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name="address",
            name="street_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="address",
            name="pincode_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
    ]
