# Generated by Django 5.1.15 on 2026-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='address',
            name='street_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'street_hash', 'pincode_hash'], name='addresses_user_id_83be4b_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='addresses_user_id_41b398_idx'),
        ),
    ]
